#------------------------------------------------------------
# Values for this lesson.
#------------------------------------------------------------

# Which carpentry is this (swc, dc, lc, or cp)?
# swc: Software Carpentry
# dc: Data Carpentry
# lc: Library Carpentry
# cp: Carpentries (to use for instructor training for instance)
# incubator: The Carpentries Incubator
# 
# This option supports custom types so lessons can be branded
# and themed with your own logo and alt-text (see `carpentry_description`)
# See https://carpentries.github.io/sandpaper-docs/editing.html#adding-a-custom-logo
carpentry: 'incubator'

# Alt-text description of the lesson.
carpentry_description: 'Byte-sized RSE'

# Overall title for pages.
title: 'Byte-sized RSE' 

# Date the lesson was created (YYYY-MM-DD, this is empty by default)
created: 2025-01-15

# Comma-separated list of keywords for the lesson
keywords: 'software, RSE, research software, development, practices' 

# Life cycle stage of the lesson
# possible values: pre-alpha, alpha, beta, stable
life_cycle: 'pre-alpha'

# License of the lesson
license: 'CC-BY 4.0'

# Link to the source repository for this lesson
source: 'https://github.com/softwaresaved/byte-sized-rse'

# Default branch of your lesson
branch: 'main'

# Who to contact if there are any issues
contact: 'team@carpentries.org' # FIXME

# Navigation ------------------------------------------------
#
# Use the following menu items to specify the order of
# individual pages in each dropdown section. Leave blank to
# include all pages in the folder.
#
# Example -------------
#
# episodes:
# - introduction.md
# - first-steps.md
#
# learners:
# - setup.md
#
# instructors:
# - instructor-notes.md
#
# profiles:
# - one-learner.md
# - another-learner.md

# Disable sidebar automatic numbering
disable_sidebar_numbering: true

# Order of episodes in your lesson
episodes: 
- 10-introduction.md
- 11-setup.md
- 12-running-vscode.md
- 13-code-editor.md
- 14-running-debugging.md
- 20-introduction.md
- 21-setup.md
- 22-example-code.md
- 23-analysing-code.md
- 24-linter-advanced.md
- 30-introduction.md
- 31-setup.md
- 32-example-code.md
- 33-feature-branch.md
- 34-pull-request.md
- 35-merge-pr.md
- 36-merge-conflicts.md
- 40-introduction.md
- 41-setup.md
- 42-example-code.md
- 43-repo-issue-fixing.md
- 44-create-pull-request.md
- 45-review-pull-request.md
- 46-merge-pull-request.md
- 50-introduction.md
- 51-setup.md
- 52-example-code.md
- 53-create-new-test.md
- 54-handling-errors.md
- 60-introduction.md
- 61-setup.md
- 62-example-code.md
- 63-defining-a-workflow.md
- 64-tracking-running-workflows.md
- 65-build-matrices.md

# Information for Learners
learners: 

# Information for Instructors
instructors: 

# Learner Profiles
profiles: 

# Customisation ---------------------------------------------
#
# This space below is where custom yaml items (e.g. pinning
# sandpaper and varnish versions) should live


